// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peluqueria.Data;

namespace Peluqueria.Migrations
{
    [DbContext(typeof(PeluqueriaContext))]
    [Migration("20191027203039_add-last-haircut-to-client")]
    partial class addlasthaircuttoclient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Peluqueria.Models.Barbershop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance");

                    b.Property<string>("Name");

                    b.Property<string>("Number");

                    b.Property<string>("Street");

                    b.HasKey("ID");

                    b.ToTable("Barbershops");
                });

            modelBuilder.Entity("Peluqueria.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance");

                    b.Property<int?>("BarbershopID");

                    b.Property<int?>("HairCutID");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("BarbershopID");

                    b.HasIndex("HairCutID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Peluqueria.Models.HairCut", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BarbershopID");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("ID");

                    b.HasIndex("BarbershopID");

                    b.ToTable("HairCuts");
                });

            modelBuilder.Entity("Peluqueria.Models.Client", b =>
                {
                    b.HasOne("Peluqueria.Models.Barbershop")
                        .WithMany("Clients")
                        .HasForeignKey("BarbershopID");

                    b.HasOne("Peluqueria.Models.HairCut", "LastHairCut")
                        .WithMany()
                        .HasForeignKey("HairCutID");
                });

            modelBuilder.Entity("Peluqueria.Models.HairCut", b =>
                {
                    b.HasOne("Peluqueria.Models.Barbershop")
                        .WithMany("HairCuts")
                        .HasForeignKey("BarbershopID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
